#!/usr/bin/env ruby
#^syntax detection

config Hash[
  :domain => "default.zone"
]

node :localhost do

  provider    TestLab::Provider::Vagrant
  config      Hash[
    :vagrant => {
      :id       => "mytestlab-#{ENV['USER']}".downcase,
      :ip       => "192.168.255.1",
      :user     => "vagrant",
      :port     => 22,
      :cpus     => 1,
      :memory   => 512
    },
    :repo => File.dirname(__FILE__)
  ]

  route        false

  network :testnet do
    address '192.168.255.254/16'
    bridge  :br0
  end

  container "server-1" do
    distro        "ubuntu"
    release       "precise"

    interface do
      name       :eth0
      network_id :testnet
      address    '192.168.0.254/16'
      primary    true
    end

    interface do
      name       :eth1
      network_id :testnet
      address    '192.168.0.253/16'
    end
  end

  container "server-2" do
    distro        "ubuntu"
    release       "precise"

    interface do
      name       :eth0
      network_id :testnet
      address    '192.168.0.200/16'
    end
  end

end
